substitutions:
  name: hewalex-g422-modbus
  device_description: "Monitor and control a Hewalex G422 System via RS485"
  external_components_source: github://smaksimowicz/esphome-hewalex-g422@main
  tx_pin: GPIO17
  rx_pin: GPIO16
  rx_timeout: 450ms

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "smaksimowicz.esphome-hewalex-g422"
    version: 1.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: "650b8cb93a5046cf2743b6316e8dad70"

 

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  id: mqtt_client

api:
 encryption:
    key: "Lo9In/3ETuMTmgRLXx0gnHGsWRIJgNpCas7wV4kd4aI="

uart:
  - id: uart_0
    baud_rate: 115200
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}

hewalex_g422:
  - id: g422_0   
    update_interval: 2s
    rx_timeout: ${rx_timeout}

sensor:
  - platform: hewalex_g422
    hewalex_g422_id: g422_0
    temperature_1:
      name: "T1" 
    temperature_2:
      name: "T2"   