substitutions:
  name: hewalex-g422-modbus
  device_description: "Monitor and control a Hewalex G422 System via RS485"
  external_components_source: github://smaksimowicz/esphome-hewalex-g422@main
  tx_pin: GPIO17
  rx_pin: GPIO16
  rx_timeout: 150ms

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "smaksimowicz.esphome-hewalex-g422"
    version: 1.0.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  level: ERROR

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

  uart:
    - id: uart_0
      baud_rate: 115200
      tx_pin: ${tx_pin}
      rx_pin: ${rx_pin}
  
  hewalex_g422:
    - id: g422_0   
      update_interval: 2s
      rx_timeout: ${rx_timeout}
  
  sensor:
    - platform: hewalex_g422
      hewalex_g422_id: g422_0
      temperature_1:
        name: "T1 (Collectors temp)" 
      temperature_2:
        name: "T2 (Tank bottom temp)"   
      temperature_3:
        name: "T3 (Air separator temp)"  
      temperature_4:
        name: "T4 (Tank top temp)" 
      temperature_5:
        name: "T5 (Boiler outlet temp)" 
      temperature_6:
        name: "T6 ()" 
      collector_power:
        name: "Collector Power (W)"
      consumption_w:  
        name: "Consumption (W)"
      collector_active:  
        name: "Collector Active (1/0)"
      flow_rate:
        name: "Flow Rate (l/min)"
        unit_of_measurement: "l/min"
      collector_pump_on:
        name: "Collector Pump (P) ON (1/0)"
      boiler_pump_on:
        name: "Boiler Pump (K) ON (1/0)" 
      circulation_pump_on:
        name: "Circulation Pump (C) ON (1/0)"
      collector_pump_speed:
        name: "Collector Pump Speed (0-15)" 
      total_energy_kwh:
        name: "Total Energy (kWh)"  

      